name:                aoc
version:             0.1.0.0
github:              "cmann/aoc"
license:             BSD3
author:              "Cameron Mann"
maintainer:          "camthemann@gmail.com"
copyright:           "2020 Cameron Mann"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- split
